name: Build Nativo Manjaro ARM

on:
  push:
    tags:
      - 'v*'

jobs:
  build-native-arm:
    runs-on: self-hosted

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build project natively
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)

      - name: Prepare binary
        run: |
          mv build/Maxicajero-Server-aarch64 ./Maxicajero-Server-aarch64

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: Maxicajero-Server-aarch64
          body: "${{ github.event.head_commit.message }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}