name: Build Nativo Manjaro ARM

on:
  push:
    tags:
      - 'v*' # Se dispara al subir un tag (ej. v2.1.1)

jobs:
  build-native-arm:
    runs-on: self-hosted # <--- Aquí le dices que corra en tu Raspberry Pi

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 1. Compilar directamente en la Raspberry Pi (usando el CMake y Make locales)
      - name: Build project natively
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)

      # 2. Preparar el binario resultante
      - name: Prepare binary
        run: |
          mv build/Maxicajero-Server-aarch64 ./Maxicajero-Server-aarch64

      # 3. Subir automáticamente a GitHub Releases
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: Maxicajero-Server-aarch64
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}